package com.apap.director.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONTACT".
 */
@Entity
public class Contact {

    @Id
    @NotNull
    private String name;

    @Generated
    public Contact() {
    }

    @Generated
    public Contact(String name) {
        this.name = name;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }

}
