package com.apap.director.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONVERSATION".
 */
@Entity
public class Conversation {

    @Id
    private Long id;

    @NotNull
    private String sender;

    @Id
    @NotNull
    private String recipient;

    @Generated
    public Conversation() {
    }

    public Conversation(Long id, String recipient) {
        this.id = id;
        this.recipient = recipient;
    }

    @Generated
    public Conversation(Long id, String sender, String recipient) {
        this.id = id;
        this.sender = sender;
        this.recipient = recipient;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getSender() {
        return sender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSender(@NotNull String sender) {
        this.sender = sender;
    }

    @NotNull
    public String getRecipient() {
        return recipient;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecipient(@NotNull String recipient) {
        this.recipient = recipient;
    }

}
