package com.apap.director.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MESSAGE".
 */
@Entity
public class Message {

    @Id
    private Long id;

    @NotNull
    private String sender;

    @NotNull
    private String recipient;
    private String content;
    private java.util.Date date;

    @Generated
    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    @Generated
    public Message(Long id, String sender, String recipient, String content, java.util.Date date) {
        this.id = id;
        this.sender = sender;
        this.recipient = recipient;
        this.content = content;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getSender() {
        return sender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSender(@NotNull String sender) {
        this.sender = sender;
    }

    @NotNull
    public String getRecipient() {
        return recipient;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecipient(@NotNull String recipient) {
        this.recipient = recipient;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
