package com.apap.director.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MESSAGE".
 */
@Entity
public class Message {
    private String sender;
    private String recipient;
    private String content;
    private java.util.Date date;
    private long conversationId;

    @Generated
    public Message() {
    }

    @Generated
    public Message(String sender, String recipient, String content, java.util.Date date, long conversationId) {
        this.sender = sender;
        this.recipient = recipient;
        this.content = content;
        this.date = date;
        this.conversationId = conversationId;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getRecipient() {
        return recipient;
    }

    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public long getConversationId() {
        return conversationId;
    }

    public void setConversationId(long conversationId) {
        this.conversationId = conversationId;
    }

    @Override
    public String toString() {
        return content;
    }

}
